import { Country } from '../interfaces/country.interface'; 

export var countries: Country [] = [
    { code:"ES", name:"España" },
    { code:"AD", name:"Andorra" },
    { code:"FR", name:"Francia" },
    { code:"PT", name:"Portugal" },
    { code:"IT", name:"Italia" },
    { code:"DE", name:"Alemania" },
    { code:"MA", name:"Marruecos" },
    { code:"DZ", name:"Argelia" },
    { code:"AR", name:"Argentina" },
    { code:"CO", name:"Colombia" },
    { code:"EC", name:"Ecuador" },
    { code:"BR", name:"Brasil" },
    { code:"BO", name:"Bolivia (Estado Plurinacional de)" },
    { code:"MX", name:"México" },
    { code:"VE", name:"Venezuela (República Bolivariana de)" },
    { code:"CL", name:"Chile" },
    { code:"PE", name:"Perú" },
    { code:"PH", name:"Filipinas" },
    { code:"CU", name:"Cuba" },
    { code:"AF", name:"Afganistán" },
    { code:"AL", name:"Albania" },
    { code:"AS", name:"Samoa Americana" },
    { code:"AO", name:"Angola" },
    { code:"AI", name:"Anguila" },
    { code:"AG", name:"Antigua y Barbuda" },
    { code:"AM", name:"Armenia" },
    { code:"AW", name:"Aruba" },
    { code:"AU", name:"Australia" },
    { code:"AT", name:"Austria" },
    { code:"AZ", name:"Azerbaiyán" },
    { code:"BS", name:"Bahamas" },
    { code:"BH", name:"Baréin" },
    { code:"BD", name:"Bangladés" },
    { code:"BB", name:"Barbados" },
    { code:"BY", name:"Bielorrusia" },
    { code:"BE", name:"Bélgica" },
    { code:"BZ", name:"Belice" },
    { code:"BJ", name:"Benín" },
    { code:"BM", name:"Bermudas" },
    { code:"BT", name:"Bután" },
    { code:"BQ", name:"Bonaire, San Eustaquio y Saba" },
    { code:"BA", name:"Bosnia y Herzegovina" },
    { code:"BW", name:"Botsuana" },
    { code:"BV", name:"Isla Bouvet" },
    { code:"IO", name:"Territorio Británico del Océano Índico" },
    { code:"BN", name:"Brunéi Darussalam" },
    { code:"BG", name:"Bulgaria" },
    { code:"BF", name:"Burkina Faso" },
    { code:"BI", name:"Burundi" },
    { code:"CV", name:"Cabo Verde" },
    { code:"KH", name:"Camboya" },
    { code:"CM", name:"Camerún" },
    { code:"CA", name:"Canadá" },
    { code:"KY", name:"Islas Caimán" },
    { code:"CF", name:"República Centroafricana" },
    { code:"TD", name:"Chad" },
    { code:"CN", name:"China" },
    { code:"CX", name:"Isla de Navidad" },
    { code:"CC", name:"Islas Cocos (Keeling)" },
    { code:"KM", name:"Comoras" },
    { code:"CD", name:"República Democrática del Congo" },
    { code:"CG", name:"Congo" },
    { code:"CK", name:"Islas Cook" },
    { code:"CR", name:"Costa Rica" },
    { code:"HR", name:"Croacia" },
    { code:"CW", name:"Curazao" },
    { code:"CY", name:"Chipre" },
    { code:"CZ", name:"Chequia" },
    { code:"CI", name:"Côte d'Ivoire (Costa de Marfil)" },
    { code:"DK", name:"Dinamarca" },
    { code:"DJ", name:"Yibuti" },
    { code:"DM", name:"Dominica" },
    { code:"DO", name:"República Dominicana" },
    { code:"EG", name:"Egipto" },
    { code:"SV", name:"El Salvador" },
    { code:"GQ", name:"Guinea Ecuatorial" },
    { code:"ER", name:"Eritrea" },
    { code:"EE", name:"Estonia" },
    { code:"SZ", name:"Esuatini" },
    { code:"ET", name:"Etiopía" },
    { code:"FK", name:"Islas Malvinas (Falkland Islands)" },
    { code:"FO", name:"Islas Feroe" },
    { code:"FJ", name:"Fiyi" },
    { code:"FI", name:"Finlandia" },
    { code:"GF", name:"Guayana Francesa" },
    { code:"PF", name:"Polinesia Francesa" },
    { code:"TF", name:"Tierras Australes y Antárticas Francesas" },
    { code:"GA", name:"Gabón" },
    { code:"GM", name:"Gambia" },
    { code:"GE", name:"Georgia" },
    { code:"GH", name:"Ghana" },
    { code:"GR", name:"Grecia" },
    { code:"GL", name:"Groenlandia" },
    { code:"GD", name:"Granada" },
    { code:"GP", name:"Guadalupe" },
    { code:"GU", name:"Guam" },
    { code:"GT", name:"Guatemala" },
    { code:"GG", name:"Guernesey" },
    { code:"GN", name:"Guinea" },
    { code:"GW", name:"Guinea-Bisáu" },
    { code:"GY", name:"Guyana" },
    { code:"HT", name:"Haití" },
    { code:"HM", name:"Islas Heard y McDonald" },
    { code:"VA", name:"Santa Sede (Ciudad del Vaticano)" },
    { code:"HN", name:"Honduras" },
    { code:"HK", name:"Hong Kong" },
    { code:"HU", name:"Hungría" },
    { code:"IS", name:"Islandia" },
    { code:"IN", name:"India" },
    { code:"ID", name:"Indonesia" },
    { code:"IR", name:"Irán (República Islámica del)" },
    { code:"IQ", name:"Irak" },
    { code:"IE", name:"Irlanda" },
    { code:"IM", name:"Isla de Man" },
    { code:"IL", name:"Israel" },
    { code:"JM", name:"Jamaica" },
    { code:"JP", name:"Japón" },
    { code:"JE", name:"Jersey" },
    { code:"JO", name:"Jordania" },
    { code:"KZ", name:"Kazajistán" },
    { code:"KE", name:"Kenia" },
    { code:"KI", name:"Kiribati" },
    { code:"KP", name:"Corea (República Popular Democrática de)" },
    { code:"KR", name:"Corea (República de)" },
    { code:"KW", name:"Kuwait" },
    { code:"KG", name:"Kirguistán" },
    { code:"LA", name:"República Democrática Popular Lao" },
    { code:"LV", name:"Letonia" },
    { code:"LB", name:"Líbano" },
    { code:"LS", name:"Lesoto" },
    { code:"LR", name:"Liberia" },
    { code:"LY", name:"Libia" },
    { code:"LI", name:"Liechtenstein" },
    { code:"LT", name:"Lituania" },
    { code:"LU", name:"Luxemburgo" },
    { code:"MO", name:"Macao" },
    { code:"MG", name:"Madagascar" },
    { code:"MW", name:"Malaui" },
    { code:"MY", name:"Malasia" },
    { code:"MV", name:"Maldivas" },
    { code:"ML", name:"Malí" },
    { code:"MT", name:"Malta" },
    { code:"MH", name:"Islas Marshall" },
    { code:"MQ", name:"Martinica" },
    { code:"MR", name:"Mauritania" },
    { code:"MU", name:"Mauricio" },
    { code:"YT", name:"Mayotte" },
    { code:"FM", name:"Micronesia" },
    { code:"MD", name:"República de Moldavia" },
    { code:"MC", name:"Mónaco" },
    { code:"MN", name:"Mongolia" },
    { code:"ME", name:"Montenegro" },
    { code:"MS", name:"Montserrat" },
    { code:"MZ", name:"Mozambique" },
    { code:"MM", name:"Myanmar" },
    { code:"NA", name:"Namibia" },
    { code:"NR", name:"Nauru" },
    { code:"NP", name:"Nepal" },
    { code:"NL", name:"Países Bajos" },
    { code:"NC", name:"Nueva Caledonia" },
    { code:"NZ", name:"Nueva Zelanda" },
    { code:"NI", name:"Nicaragua" },
    { code:"NE", name:"Níger" },
    { code:"NG", name:"Nigeria" },
    { code:"NU", name:"Niue" },
    { code:"NF", name:"Isla Norfolk" },
    { code:"MK", name:"Macedonia del Norte" },
    { code:"MP", name:"Islas Marianas del Norte" },
    { code:"NO", name:"Noruega" },
    { code:"OM", name:"Omán" },
    { code:"PK", name:"Pakistán" },
    { code:"PW", name:"Palaos" },
    { code:"PA", name:"Panamá" },
    { code:"PG", name:"Papúa Nueva Guinea" },
    { code:"PY", name:"Paraguay" },
    { code:"PL", name:"Polonia" },
    { code:"QA", name:"Catar" },
    { code:"RE", name:"Reunión" },
    { code:"RO", name:"Rumanía" },
    { code:"RU", name:"Federación Rusa" },
    { code:"RW", name:"Ruanda" },
    { code:"BL", name:"San Bartolomé" },
    { code:"SH", name:"Santa Elena, Ascensión y Tristán de Acuña" },
    { code:"KN", name:"San Cristóbal y Nieves" },
    { code:"LC", name:"Santa Lucía" },
    { code:"MF", name:"San Martín (parte francesa)" },
    { code:"PM", name:"San Pedro y Miquelón" },
    { code:"VC", name:"San Vicente y las Granadinas" },
    { code:"WS", name:"Samoa" },
    { code:"SM", name:"San Marino" },
    { code:"ST", name:"Santo Tomé y Príncipe" },
    { code:"SA", name:"Arabia Saudí" },
    { code:"SN", name:"Senegal" },
    { code:"RS", name:"Serbia" },
    { code:"SC", name:"Seychelles" },
    { code:"SL", name:"Sierra Leona" },
    { code:"SG", name:"Singapur" },
    { code:"SX", name:"Sint Maarten (parte neerlandesa)" },
    { code:"SK", name:"Eslovaquia" },
    { code:"SI", name:"Eslovenia" },
    { code:"SB", name:"Islas Salomón" },
    { code:"SO", name:"Somalia" },
    { code:"ZA", name:"Sudáfrica" },
    { code:"GS", name:"Georgia del Sur y las Islas Sandwich del Sur" },
    { code:"SS", name:"Sudán del Sur" },
    { code:"ES", name:"España" },
    { code:"LK", name:"Sri Lanka" },
    { code:"SD", name:"Sudán" },
    { code:"SR", name:"Surinam" },
    { code:"SJ", name:"Islas Svalbard y Jan Mayen" },
    { code:"SE", name:"Suecia" },
    { code:"CH", name:"Suiza" },
    { code:"SY", name:"República Árabe Siria" },
    { code:"TW", name:"Taiwán" },
    { code:"TJ", name:"Tayikistán" },
    { code:"TZ", name:"Tanzania" },
    { code:"TH", name:"Tailandia" },
    { code:"TL", name:"Timor-Leste" },
    { code:"TG", name:"Togo" },
    { code:"TK", name:"Tokelau" },
    { code:"TO", name:"Tonga" },
    { code:"TT", name:"Trinidad y Tobago" },
    { code:"TN", name:"Túnez" },
    { code:"TR", name:"Turquía" },
    { code:"TM", name:"Turkmenistán" },
    { code:"TC", name:"Islas Turcas y Caicos" },
    { code:"TV", name:"Tuvalu" },
    { code:"UG", name:"Uganda" },
    { code:"UA", name:"Ucrania" },
    { code:"AE", name:"Emiratos Árabes Unidos" },
    { code:"GB", name:"Reino Unido de Gran Bretaña e Irlanda del Norte" },
    { code:"US", name:"Estados Unidos de América" },
    { code:"UY", name:"Uruguay" },
    { code:"UZ", name:"Uzbekistán" },
    { code:"VU", name:"Vanuatu" },
    { code:"VE", name:"Venezuela (República Bolivariana de)" },
    { code:"VN", name:"Vietnam" },
    { code:"WF", name:"Wallis y Futuna" },
    { code:"EH", name:"Sahara Occidental" },
    { code:"YE", name:"Yemen" },
    { code:"ZM", name:"Zambia" },
    { code:"ZW", name:"Zimbabue" }
];
