import { DiagnosticTest } from "../interfaces/diagnostic-test.interface";

export var diagnosticTests: DiagnosticTest[] = [
    { code: "HEMOGRAM", name: "Hemograma completo" },
    { code: "GLUCOSE", name: "Glucosa en sangre (en ayunas)" },
    { code: "LIPID_PROFILE", name: "Perfil lipídico" },
    { code: "LIVER_FUNCTION", name: "Función hepática (ALT, AST, bilirrubina, fosfatasa alcalina)" },
    { code: "RENAL_FUNCTION", name: "Función renal (creatinina, urea, electrolitos)" },
    { code: "HbA1c", name: "Hemoglobina glicosilada" },
    { code: "VITAMIN_D", name: "Niveles de vitamina D" },
    { code: "VITAMIN_B12", name: "Niveles de vitamina B12" },
    { code: "THYROID", name: "Hormonas tiroideas (TSH, T3, T4)" },
    { code: "TUMOR_MARKERS", name: "Marcadores tumorales (PSA, CA-125, CEA, AFP)" },
    { code: "COAGULATION", name: "Prueba de coagulación (TP, TTPa)" },
    { code: "ANA", name: "Anticuerpos antinucleares (ANA)" },
    { code: "PREGNANCY", name: "Prueba de embarazo (hCG)" },
    { code: "CHEST_XRAY", name: "Radiografía de tórax" },
    { code: "CT_SCAN", name: "Tomografía computarizada (CT)" },
    { code: "MRI", name: "Resonancia magnética (MRI)" },
    { code: "ULTRASOUND", name: "Ultrasonido (ecografía)" },
    { code: "MAMMOGRAPHY", name: "Mamografía" },
    { code: "BONE_DENSITOMETRY", name: "Densitometría ósea" },
    { code: "ANGIOGRAPHY", name: "Angiografía" },
    { code: "PULMONARY_FUNCTION", name: "Pruebas de función pulmonar (espirometría)" },
    { code: "ECG", name: "Electrocardiograma (ECG)" },
    { code: "EEG", name: "Electroencefalograma (EEG)" },
    { code: "ECHO", name: "Ecocardiograma" },
    { code: "COLONOSCOPY", name: "Colonoscopia" },
    { code: "BLOOD_CULTURE", name: "Cultivo sanguíneo" },
    { code: "URINALYSIS", name: "Análisis de orina" },
    { code: "STREP_TEST", name: "Prueba de estreptococo" },
    { code: "TB_TEST", name: "Prueba de tuberculosis (tuberculina)" },
    { code: "HIV_TEST", name: "Prueba de VIH" },
    { code: "HEPATITIS_TEST", name: "Prueba de hepatitis (A, B, C)" },
    { code: "STOOL_TEST", name: "Examen de heces" },
    { code: "CTG", name: "Cardiotocografía (monitoreo fetal)" },
    { code: "HBA1C", name: "Hemoglobina A1c" },
    { code: "DOPPLER", name: "Doppler (estudio de flujo sanguíneo)" },
    { code: "SKIN_BIOPSY", name: "Biopsia de piel" },
    { code: "LUNG_BIOPSY", name: "Biopsia pulmonar" },
    { code: "LIVER_BIOPSY", name: "Biopsia hepática" },
    { code: "BLOOD_GAS", name: "Gases en sangre (pH, O2, CO2)" },
    { code: "CERVICAL_CANCER_SCREEN", name: "Papanicolau (cáncer cervical)" },
    { code: "PROSTATE_CANCER_SCREEN", name: "Examen de cáncer de próstata (DRE, PSA)" },
    { code: "ELECTROLYTES", name: "Electrolitos (Na+, K+, Cl-)" },
    { code: "VIRAL_LOAD", name: "Carga viral (VIH, hepatitis)" },
    { code: "HEART_RATE_MONITOR", name: "Monitoreo de frecuencia cardíaca" },
    { code: "CAROTID_ULTRASOUND", name: "Ultrasonido de arterias carótidas" },
    { code: "HORMONAL_PROFILE", name: "Perfil hormonal (FSH, LH, estradiol, progesterona)" },
    { code: "RAPID_FLU_TEST", name: "Prueba rápida de influenza" },
    { code: "URINE_CULTURE", name: "Cultivo de orina" },
    { code: "STOMACH_ULTRASOUND", name: "Ultrasonido de estómago" },
    { code: "CT_ABD", name: "Tomografía computarizada de abdomen" },
    { code: "NATURAL_KILLER_CELLS", name: "Contar células asesinas naturales (NK)" },
    { code: "CYSTIC_FIBROSIS", name: "Prueba de fibrosis quística" },
    { code: "HUMAN_GENE_TEST", name: "Prueba de genes humanos (mutaciones genéticas)" },
    { code: "FERRITIN", name: "Niveles de ferritina (indicador de hierro)" },
    { code: "HYPERCOAGULABILITY_TEST", name: "Pruebas de hipocoagulabilidad (factor V Leiden, mutaciones)" },
    { code: "SICKLE_CELL_TEST", name: "Prueba de células falciformes" },
    { code: "VIRAL_HEPATITIS", name: "Hepatitis viral (serología)" },
    { code: "MALARIAL_TEST", name: "Prueba de malaria" },
    { code: "ZIKA_TEST", name: "Prueba de Zika" },
    { code: "CHIKUNGUNYA_TEST", name: "Prueba de Chikungunya" },
    { code: "SEPSIS_TEST", name: "Prueba de sepsis" },
    { code: "LUNG_FUNCTION", name: "Pruebas de función pulmonar (espirómetro)" },
    { code: "HEART_FUNCTION", name: "Ecocardiograma doppler (función cardíaca)" },
    { code: "BLOOD_TYPE", name: "Tipo de sangre" },
    { code: "GENETIC_SCREENING", name: "Cribado genético" },
    { code: "LIPASE", name: "Nivel de lipasa (indicador de pancreatitis)" },
    { code: "AMYLASE", name: "Nivel de amilasa (indicador de pancreatitis)" },
    { code: "HOMOCYSTEINE", name: "Nivel de homocisteína" },
    { code: "INR", name: "International Normalized Ratio (INR)" },
    { code: "MONONUCLEOSIS", name: "Prueba de mononucleosis infecciosa" }
];
